name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Yeabtsega-Tesfaye
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake to output branch
        run: |
          mkdir -p output
          cp dist/github-contribution-grid-snake.svg output/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generate snake"
          git push origin HEAD:output
